SWS.WebApp/Areas/Admin/Controllers/BlockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using SWS.WebApp.Areas.Admin.Mappers.BlockMappers;
using Kendo.Mvc.UI;
using SWS.Common;
using SWS.Services.BlockServices;
using SWS.WebApp.Areas.Admin.Models.BlockModels;
using SWS.Services.LanguageServices;
using SWS.WebApp.Areas.Admin.Mappers.LocalizationMapper;

namespace SWS.WebApp.Areas.Admin.Controllers
{
    public class BlockController : Controller
    {
        private readonly IBlockService blockService;
        private readonly ILanguageService languageService;

        public BlockController()
        {
            SWSContext db = new SWSContext();
            blockService = new BlockService(db);
            languageService = new LanguageService(db);
        }

        // GET: /Admin/PageType/
        public ActionResult Index()
        {
            var pageTypeModelItems = blockService.GetAll().ToList().ToModel();
            return View(pageTypeModelItems);
        }

        [ChildActionOnly]
        public ActionResult LocalizationBlockEditor(int index, LocalizedBlockValueModel model)
        {
            ViewBag.Index = index;
            return PartialView(model);
        }

        public ActionResult Create()
        {
            var languages = languageService.GetAll();
            if (languages != null && languages.Count > 0)
            {
                var langugeModelItems = languages.ToModel();
                ViewBag.Languages = languageService.GetAll().ToList().ToModel();
                CreateBlockModel model = new CreateBlockModel();
                PrepareCreateModel(model);
                return View(model);
            }
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create(CreateBlockModel model)
        {
            if (ModelState.IsValid)
            {
                blockService.Add(model.ToEntity());
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Edit([DataSourceRequest] DataSourceRequest request, EditBlockModel model)
        {
            if (ModelState.IsValid)
            {
                blockService.Update(model.ToEntity());
            }
            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Delete([DataSourceRequest] DataSourceRequest request, EditBlockModel model)
        {
            if (ModelState.IsValid)
            {
                blockService.Delete(model.Id);
            }
            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }

        private void PrepareCreateModel(CreateBlockModel model)
        {
            var languages = languageService.GetAll();
            foreach (var lang in languages)
            {
                model.LocalizedBlockValues.Add(new LocalizedBlockValueModel { 
                    LanguageId = lang.Id,
                    LanguageKey = lang.LanguageKey
                });
            }
        }
    }
}

SWS.WebApp/Areas/Admin/Controllers/DashboardController.cs
using SWS.Common;
using SWS.Services.PageTypeServices;
using SWS.WebApp.Connections;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SWS.WebApp.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IPageTypeService pageTypeService;

        public DashboardController()
        {
            this.pageTypeService = new PageTypeService(new SWSContext());
        }

        //
        // GET: /Admin/Dashboard/
        public ActionResult Index()
        {
            pageTypeService.Add(new Common.PageType() { 
                Name = "Test",
                ShortDescription = "short description"
            });
            return View();
        }
	}
}

SWS.WebApp/Areas/Admin/Controllers/LocalizationController.cs
using SWS.Common;
using SWS.Services.LanguageServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SWS.WebApp.Areas.Admin.Mappers.LocalizationMapper;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using SWS.WebApp.Areas.Admin.Models.LocalizationModels;
using System.IO;

namespace SWS.WebApp.Areas.Admin.Controllers
{
    public class LocalizationController : Controller
    {
        private readonly ILanguageService languageService;
        public LocalizationController()
        {
            SWSContext db = new SWSContext();
            languageService = new LanguageService(db);
        }

        // GET: /Admin/PageType/
        public ActionResult Index()
        {
            var pageTypeModelItems = languageService.GetAll().ToList().ToModel();
            return View(pageTypeModelItems);
        }

        public ActionResult Create()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create(CreateLocalizationModel model, HttpPostedFileBase attachment)
        {
            if (attachment != null)
            {
                var fileName = Path.GetFileName(attachment.FileName);
                var destinationPath = Path.Combine(Server.MapPath("~/Content/SWS/Localizations"), fileName);
                attachment.SaveAs(destinationPath);
                model.Icon = destinationPath;
            }

            if (ModelState.IsValid)
            {
                languageService.Add(model.ToEntity());
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            Language entity = languageService.Get(id);
            return View(entity.ToModel());
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Edit([DataSourceRequest] DataSourceRequest request, EditLocalizationModel model, HttpPostedFileBase attachment)
        {
            if (attachment != null)
            {
                var fileName = Path.GetFileName(attachment.FileName);
                var destinationPath = Path.Combine(Server.MapPath("~/Content/SWS/Localizations"), fileName);
                attachment.SaveAs(destinationPath);

                System.IO.File.Delete(model.Icon); // remove previous file
                model.Icon = destinationPath;
            }

            if (ModelState.IsValid)
            {
                languageService.Update(model.ToEntity());
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Delete(int id)
        {
            if (ModelState.IsValid)
            {
                Language language = languageService.Get(id);
                System.IO.File.Delete(language.Icon); // remove file
                languageService.Delete(language.Id);
            }
            return RedirectToAction("Index");
        }
    }
}

SWS.WebApp/Areas/Admin/Controllers/PageTypeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SWS.Common;
using SWS.WebApp.Areas.Admin.Mappers.PageTypeMappers;
using SWS.WebApp.Areas.Admin.Models.PageTypeModels;
using SWS.Services.PageTypeServices;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;

namespace SWS.WebApp.Areas.Admin.Controllers
{
    public class PageTypeController : Controller
    {
        private readonly IPageTypeService pageTypeService;

        public PageTypeController()
        {
            SWSContext db = new SWSContext();
            pageTypeService = new PageTypeService(db);
        }

        // GET: /Admin/PageType/
        public ActionResult Index()
        {
            var pageTypeModelItems = pageTypeService.GetAll().ToModel();
            return View(pageTypeModelItems);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Create([DataSourceRequest] DataSourceRequest request, CreatePageTypeModel model)
        {
            if (ModelState.IsValid)
            {
                pageTypeService.Add(model.ToEntity());
            }
            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Edit([DataSourceRequest] DataSourceRequest request, EditPageTypeModel model)
        {
            if (ModelState.IsValid)
            {
                pageTypeService.Update(model.ToEntity());
            }
            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Delete([DataSourceRequest] DataSourceRequest request, PageTypeModel model)
        {
            if(ModelState.IsValid)
            {
                pageTypeService.Delete(model.Id);
            }
            return Json(new[] { model }.ToDataSourceResult(request, ModelState));
        }
    }
}

SWS.WebApp/Areas/Admin/Views/Shared/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Areas/Admin/Content/AdminSite.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/kendo/2015.1.408//kendo.common.min.css" />
    <link rel="stylesheet" href="~/Content/kendo/2015.1.408/kendo.default.min.css" />

    <script src="@Url.Content("~/Scripts/kendo/2015.1.408/jquery.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2015.1.408/jszip.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2015.1.408/kendo.all.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo/2015.1.408/kendo.aspnetmvc.min.js")"></script>
    <script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
</head>
<body style="padding:20px;">
    <div>
        @(Html.Kendo().ToolBar()
        .Name("ToolBar")
        .Items(items =>
        {
            var mainLink = @Url.Action("Index", "Dashboard", new { area = "admin" });
            var pageTypeLink = @Url.Action("Index", "PageType", new { area = "admin" });
            var blockLink = @Url.Action("Index", "Block", new { area = "admin" });
            var navigationLink = @Url.Action("Index", "Navigation", new { area = "admin" });            
            var localizationLink = @Url.Action("Index", "Localization", new { area = "admin" });

            items.Add().Type(CommandType.Button).Text("Главная").Url(mainLink);
            items.Add().Type(CommandType.SplitButton).Text("Текстовие разделы").MenuButtons(menuButtons =>
            {
                menuButtons.Add().Text("Типы страниц").Url(pageTypeLink).Icon("insert-n");
                menuButtons.Add().Text("Страници").Icon("insert-m");
                menuButtons.Add().Text("Блоки").Url(blockLink).Icon("insert-s");
            });
            items.Add().Type(CommandType.Button).Text("Навигация").Url(navigationLink);
            items.Add().Type(CommandType.Button).Text("Локализация").Url(localizationLink);
        }))

        <script>
            $(document).ready(function () {
                $("#dropdown").kendoDropDownList({
                    optionLabel: "Paragraph",
                    dataTextField: "text",
                    dataValueField: "value",
                    dataSource: [
                        { text: "Heading 1", value: 1 },
                        { text: "Heading 2", value: 2 },
                        { text: "Heading 3", value: 3 },
                        { text: "Title", value: 4 },
                        { text: "Subtitle", value: 5 },
                    ]
                });
            });
        </script>
    </div>
    <div style="margin:20px;">
        @RenderBody()
    </div>
</body>
</html>